import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-raised': 'var(--color-surface-raised)',
        primary: {
          DEFAULT: 'var(--color-primary)',
          600: 'var(--color-primary-600)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          600: 'var(--color-secondary-600)',
        },
        'text-primary': 'var(--color-text-primary)',
        'text-muted': 'var(--color-text-muted)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',

        /* "Ink on Warm Paper" tokens — new screens only, see globals.css */
        ip: {
          surface: 'var(--ip-surface)',
          'surface-dim': 'var(--ip-surface-dim)',
          'surface-bright': 'var(--ip-surface-bright)',
          'container-lowest': 'var(--ip-surface-container-lowest)',
          'container-low': 'var(--ip-surface-container-low)',
          container: 'var(--ip-surface-container)',
          'container-high': 'var(--ip-surface-container-high)',
          'container-highest': 'var(--ip-surface-container-highest)',
          'on-surface': 'var(--ip-on-surface)',
          'on-surface-variant': 'var(--ip-on-surface-variant)',
          'inverse-surface': 'var(--ip-inverse-surface)',
          'inverse-on-surface': 'var(--ip-inverse-on-surface)',
          outline: 'var(--ip-outline)',
          'outline-variant': 'var(--ip-outline-variant)',
          primary: 'var(--ip-primary)',
          'primary-container': 'var(--ip-primary-container)',
          'on-primary': 'var(--ip-on-primary)',
          'on-primary-container': 'var(--ip-on-primary-container)',
          secondary: 'var(--ip-secondary)',
          'secondary-container': 'var(--ip-secondary-container)',
          'on-secondary': 'var(--ip-on-secondary)',
          'on-secondary-container': 'var(--ip-on-secondary-container)',
          tertiary: 'var(--ip-tertiary)',
          'tertiary-container': 'var(--ip-tertiary-container)',
          'on-tertiary': 'var(--ip-on-tertiary)',
          'on-tertiary-container': 'var(--ip-on-tertiary-container)',
          error: 'var(--ip-error)',
          'error-container': 'var(--ip-error-container)',
          'on-error': 'var(--ip-on-error)',
          'on-error-container': 'var(--ip-on-error-container)',
        },
      },
      fontFamily: {
        heading: ['var(--font-syne)'],
        body: ['var(--font-outfit)'],
        accent: ['var(--font-accent)'],
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        hero: 'var(--text-hero)',

        'ip-display-lg': 'var(--ip-text-display-lg)',
        'ip-display-md': 'var(--ip-text-display-md)',
        'ip-headline-sm': 'var(--ip-text-headline-sm)',
        'ip-body-lg': 'var(--ip-text-body-lg)',
        'ip-body-md': 'var(--ip-text-body-md)',
        'ip-body-sm': 'var(--ip-text-body-sm)',
        'ip-data-mono': 'var(--ip-text-data-mono)',
      },
      spacing: {
        18: '4.5rem',
        'ip-base': 'var(--ip-space-base)',
        'ip-xs': 'var(--ip-space-xs)',
        'ip-sm': 'var(--ip-space-sm)',
        'ip-md': 'var(--ip-space-md)',
        'ip-lg': 'var(--ip-space-lg)',
        'ip-xl': 'var(--ip-space-xl)',
        'ip-edge': 'var(--ip-edge-margin)',
        'ip-gutter': 'var(--ip-gutter)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        'ip-input': 'var(--ip-radius-input)',
        'ip-card': 'var(--ip-radius-card)',
        'ip-sheet': 'var(--ip-radius-sheet)',
        'ip-pill': 'var(--ip-radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        'glow-primary': 'var(--shadow-glow-primary)',
        'glow-secondary': 'var(--shadow-glow-secondary)',
      },
      transitionTimingFunction: {
        'out-expo': 'var(--ease-out-expo)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
      },
    },
  },
  plugins: [],
};
export default config;
